### ISSUE TITLE
Problems with the configuration

### ISSUE THREAD

**Issue by ingegneriadelweb** [lng2020/GOP3-blackjack-bot#9]
I don't succeed in installing this script.
First of all, when I type the first command "pip install -r requirements.txt" it tells me:
...
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.2
    Uninstalling pip-24.2:
ERROR: Could not install packages due to an OSError: [WinError 5] Accesso negato: 'c:\\python312\\scripts\\pip.exe'
Consider using the `--user` option or check the permissions.

WARNING: There was an error checking the latest version of pip.
...

Second, if I try to write the second one "python main.py"  it tells:
"
...
Traceback (most recent call last):
  File "C:\Users\tonin\Downloads\GOP3-blackjack-bot-main\main.py", line 3, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: DLL load failed while importing QtWidgets: Impossibile trovare il modulo specificato.
PS C:\Users\tonin\Downloads\GOP3-blackjack-bot-main>
...
"

I'm sure python works. I use it with other scripts.

THANKS A LOT!

**Comment by lng2020** [comment]
```
ERROR: Could not install packages due to an OSError: [WinError 5] Accesso negato: 'c:\python312\scripts\pip.exe'
Consider using the --user option or check the permissions.
```
sounds like a permission error

**Comment by ingegneriadelweb** [comment]
Ok, I've installed requirements. So, with the second instruction ("python main.py"), CLI says:

PS C:\gop3> python main.py
Traceback (most recent call last):
  File "C:\gop3\main.py", line 3, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: DLL load failed while importing QtWidgets: Impossibile trovare il modulo specificato.
PS C:\gop3>

**Comment by lng2020** [comment]
I think it's not relevant to the program. Somehow your program failed with PyQT and you better search for a similar problem with the PyQT environment on your operation systems.

**Comment by ingegneriadelweb** [comment]
Hello, I solved. Now it works, but there is another big problem. It is too slow, in fact it stands automatically before the cursor try to click the button (hit or double, for example). I can see the mouse cursor move when the hand is just ended...

**Comment by ingegneriadelweb** [comment]
YES, I DO IT. IT WORKS. THANKS!!!

**Comment by naraptk** [comment]
can u help me/
